# Generated by Django 6.0.3 on 2026-05-19 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proprietaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('ville', models.CharField(default='Yaoundé', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('prix_mensuel', models.DecimalField(decimal_places=0, max_digits=12)),
                ('caution', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('surface', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('nombre_chambre', models.PositiveIntegerField(default=1)),
                ('nombre_salle_de_bain', models.PositiveIntegerField(default=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='bien/')),
                ('statut', models.CharField(choices=[('Disponible', 'Disponible'), ('Occupé', 'Occupé'), ('En rénovation', 'En rénovation')], default='Disponible', max_length=30)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proprietaire.proprietaire')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bien.categorie')),
                ('quartier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bien.quartier')),
            ],
        ),
    ]
