# Generated by Django 6.0.3 on 2026-06-12 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeVisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_visiteur', models.CharField(max_length=100)),
                ('email_visiteur', models.EmailField(max_length=254)),
                ('telephone_visiteur', models.CharField(max_length=20)),
                ('date_visite_souhaitee', models.DateTimeField()),
                ('message', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_visite', to='bien.bien')),
            ],
        ),
    ]
