# Generated by Django 6.0.3 on 2026-05-19 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('montant_du', models.DecimalField(decimal_places=0, max_digits=12)),
                ('montant_paye', models.DecimalField(decimal_places=0, max_digits=12)),
                ('montant_restant', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('date_paiement', models.DateTimeField()),
                ('mois_concerne', models.CharField(max_length=50)),
                ('mode', models.CharField(choices=[('Espèces', 'Espèces'), ('Mobile Money', 'Mobile Money'), ('Orange Money', 'Orange Money'), ('Virement', 'Virement'), ('Cheque', 'Cheque')], default='Espèces', max_length=50)),
                ('note', models.TextField(blank=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='contrat.contrat')),
            ],
        ),
    ]
