# Generated by Django 6.0.3 on 2026-05-19 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bien', '0001_initial'),
        ('locataire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=60, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('caution', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('Actif', 'Actif'), ('Expiré', 'Expiré'), ('Résilié', 'Résilié')], default='Actif', max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bien.bien')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locataire.locataire')),
            ],
        ),
    ]
